import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from app.config import settings
from app.schemas import AgentRequest, AgentResponse, AgentTraceItem
from app.graph.workflow import agent_workflow

# Configure logging
logging.basicConfig(
    level=logging.INFO if not settings.DEBUG else logging.DEBUG,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Dify-LangGraph-Qwen Demo API",
    description="FastAPI backend integrating LangGraph and Qwen for Dify HTTP Request Node",
    version="1.0.0",
    docs_url="/docs" if settings.DEBUG else None,
    redoc_url="/redoc" if settings.DEBUG else None,
)

# Enable CORS for local development
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health")
def health_check():
    return {
        "status": "healthy", 
        "model_configured": settings.QWEN_MODEL,
        "base_url": settings.QWEN_BASE_URL
    }

@app.post("/agent/invoke", response_model=AgentResponse)
async def invoke_agent(request: AgentRequest):
    logger.info(f"Received request from user={request.user_id} with query='{request.query[:100]}...'")
    
    # Extract optional dynamic LLM config overrides from context
    context = request.context or {}
    llm_base_url = context.get("llm_base_url")
    llm_model = context.get("llm_model")
    llm_api_key = context.get("llm_api_key")
    llm_temperature = context.get("llm_temperature")
    llm_max_tokens = context.get("llm_max_tokens")
    
    # Mask API key in debug logs
    masked_key = "None"
    if llm_api_key:
        if llm_api_key == "EMPTY":
            masked_key = "EMPTY"
        else:
            masked_key = llm_api_key[:4] + "..." if len(llm_api_key) > 4 else "..."
            
    logger.info(
        f"Dynamic LLM override detected: base_url={llm_base_url}, model={llm_model}, key={masked_key}, "
        f"temp={llm_temperature}, max_tokens={llm_max_tokens}"
    )
    
    # Initialize state
    initial_state = {
        "query": request.query,
        "user_id": request.user_id,
        "context": request.context,
        "task_type": "general_chat",
        "router_output": "",
        "analysis_output": "",
        "final_answer": "",
        "agent_trace": [],
        "need_human_review": False,
        "llm_base_url": llm_base_url,
        "llm_model": llm_model,
        "llm_api_key": llm_api_key,
        "llm_temperature": llm_temperature,
        "llm_max_tokens": llm_max_tokens
    }
    
    try:
        # Invoke the LangGraph workflow
        # Runs synchronously (using thread pool in FastAPI background if desired, or directly here)
        result = agent_workflow.invoke(initial_state)
        
        # Build the structured trace items
        trace_items = []
        for trace in result.get("agent_trace", []):
            trace_items.append(AgentTraceItem(
                agent=trace.get("agent", "unknown"),
                input=trace.get("input", ""),
                output=trace.get("output", "")
            ))
            
        response = AgentResponse(
            answer=result.get("final_answer", "Error: No final answer generated by workflow."),
            task_type=result.get("task_type", "general_chat"),
            agent_trace=trace_items,
            need_human_review=result.get("need_human_review", False)
        )
        
        logger.info(f"Workflow completed successfully. task_type={response.task_type}, need_human_review={response.need_human_review}")
        return response
        
    except Exception as e:
        logger.error(f"Error executing workflow: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Internal error executing agent workflow: {str(e)}"
        )
