from pydantic import BaseModel, Field
from typing import List, Dict, Any

class AgentRequest(BaseModel):
    query: str = Field(..., description="The user query or prompt.")
    user_id: str = Field("demo_user", description="Identifier for the user.")
    context: Dict[str, Any] = Field(default_factory=dict, description="Additional context dictionary.")

class AgentTraceItem(BaseModel):
    agent: str = Field(..., description="The name of the agent node.")
    input: str = Field(..., description="The input sent to the agent.")
    output: str = Field(..., description="The output generated by the agent.")

class AgentResponse(BaseModel):
    answer: str = Field(..., description="The final structured report or answer.")
    task_type: str = Field(..., description="The determined task type.")
    agent_trace: List[AgentTraceItem] = Field(default_factory=list, description="Execution trace of the workflow.")
    need_human_review: bool = Field(False, description="Flag indicating if human review is needed.")
