from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional

class AgentRequest(BaseModel):
    query: str = Field(..., description="The user query or prompt.")
    user_id: str = Field("demo_user", description="Identifier for the user.")
    context: Dict[str, Any] = Field(default_factory=dict, description="Additional context dictionary.")

class AgentTraceItem(BaseModel):
    agent: str = Field(..., description="The name of the agent node.")
    input: str = Field(..., description="The input sent to the agent.")
    output: str = Field(..., description="The output generated by the agent.")

class OutputImage(BaseModel):
    provider: str = Field(..., description="The provider that produced the image.")
    model: Optional[str] = Field(None, description="The image model used by the provider.")
    mime_type: str = Field("image/jpeg", description="MIME type for base64 image content.")
    image_base64: Optional[str] = Field(None, description="Base64 image payload, if returned inline.")
    url: Optional[str] = Field(None, description="Image URL, if returned by the provider.")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Provider-specific metadata.")

class AgentResponse(BaseModel):
    answer: str = Field(..., description="The final structured report or answer.")
    task_type: str = Field(..., description="The determined task type.")
    agent_trace: List[AgentTraceItem] = Field(default_factory=list, description="Execution trace of the workflow.")
    need_human_review: bool = Field(False, description="Flag indicating if human review is needed.")
    error: Optional[str] = Field(None, description="Detailed error message if the call failed.")
    output_images: List[OutputImage] = Field(default_factory=list, description="Generated output images, if any.")
    warnings: List[str] = Field(default_factory=list, description="Non-fatal warnings about provider capabilities or media handling.")

class LLMTestRequest(BaseModel):
    llm_provider: str = Field(..., description="The model provider (local_qwen, minimax, or custom_openai).")
    llm_base_url: str = Field(..., description="The Base URL override for this test.")
    llm_model: str = Field(..., description="The model name override for this test.")
    llm_api_key: Optional[str] = Field("EMPTY", description="The API Key override for this test.")
