import os
import uuid
import logging
from datetime import datetime
from typing import List, Optional
from fastapi import APIRouter, HTTPException, BackgroundTasks
from pydantic import BaseModel, Field

from backend.app.company.models import (
    TaskState, ExecutionPlan, PlanStep, Artifact, StepError, StepResult
)
from backend.app.company.store import task_store
from backend.app.company.graph import company_graph, company_execution_graph

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/tasks", tags=["company"])

class CreateTaskRequest(BaseModel):
    user_query: str = Field(..., description="Prompt/Request describing the consulting goal")

def invalidate_downstream_steps(task: TaskState, target_step_id: str):
    """
    Recursively invalidates all downstream steps depending on the target_step_id.
    Resets plan step status to 'pending', clears downstream artifacts and StepResults,
    and increments the retry count on the target step.
    """
    # Create steps lookup map
    steps_map = {step.step_id: step for step in task.plan.steps}
    
    # BFS to find transitive dependency closure of steps to invalidate
    invalidated = {target_step_id}
    added = True
    while added:
        added = False
        for step in task.plan.steps:
            if step.step_id not in invalidated:
                # If this step depends on any invalidated step, it must be invalidated
                if any(dep in invalidated for dep in step.depends_on):
                    invalidated.add(step.step_id)
                    added = True
                    
    logger.info(f"Invalidating steps due to retry of '{target_step_id}': {invalidated}")
    
    # Reset states for all invalidated steps
    for step_id in invalidated:
        if step_id in steps_map:
            steps_map[step_id].status = "pending"
            
        if step_id in task.step_results:
            res = task.step_results[step_id]
            res.status = "pending"
            res.output_artifact_ids = []
            res.error = None
            res.completed_at = None
            if step_id == target_step_id:
                res.retry_count += 1
            else:
                res.retry_count = 0
        else:
            # Create a pending StepResult if none exists
            task.step_results[step_id] = StepResult(
                step_id=step_id,
                status="pending",
                retry_count=1 if step_id == target_step_id else 0
            )
                
    # Remove artifacts generated by any of the invalidated steps
    artifacts_to_keep = []
    for art in task.artifacts:
        if art.source_step_id in invalidated:
            try:
                local_path = task_store.workspace_root.joinpath(art.path_or_url)
                if local_path.exists() and local_path.is_file():
                    os.remove(local_path)
                    logger.info(f"Deleted invalidated artifact file: {local_path}")
            except Exception as e:
                logger.warning(f"Failed to delete invalidated artifact file {art.path_or_url}: {e}")
        else:
            artifacts_to_keep.append(art)
    task.artifacts = artifacts_to_keep


async def run_execution_graph(task_id: str):
    """Background task runner to execute the sequential graph and handle top level exceptions."""
    try:
        task = task_store.load_task(task_id)
        if not task:
            logger.error(f"Task {task_id} not found for background execution.")
            return
        
        if task.status != "executing":
            logger.warning(f"Task {task_id} status is '{task.status}', not 'executing'. Aborting background run.")
            return
            
        await company_execution_graph.ainvoke({"task_id": task_id})
    except Exception as e:
        logger.exception(f"Exception in background run for task {task_id}")
        task = task_store.load_task(task_id)
        if task:
            task.status = "failed"
            task.error = StepError(
                error_type="worker_error",
                message=f"Background execution exception: {str(e)}",
                details={}
            )
            task.completed_at = datetime.now().isoformat()
            task.updated_at = datetime.now().isoformat()
            task_store.save_task(task)


@router.post("", response_model=dict)
async def create_task(req: CreateTaskRequest):
    """
    Creates a new multi-agent consulting task.
    Invokes the Supervisor planning node synchronously to construct the JSON execution plan.
    """
    task_id = f"task_{int(datetime.now().timestamp())}_{uuid.uuid4().hex[:6]}"
    now_iso = datetime.now().isoformat()
    
    task = TaskState(
        task_id=task_id,
        user_query=req.user_query,
        status="planning",
        created_at=now_iso,
        updated_at=now_iso
    )
    task_store.save_task(task)
    
    try:
        await company_graph.ainvoke({"task_id": task_id})
    except Exception as e:
        logger.exception(f"Planning failed during initial creation of task {task_id}")
        # Mark as planning failed
        task = task_store.load_task(task_id)
        if task and task.status == "planning":
            task.status = "planning_failed"
            task.error = StepError(
                error_type="validation_error",
                message=f"Plan generation failed with error: {str(e)}",
                details={}
            )
            task.updated_at = datetime.now().isoformat()
            task_store.save_task(task)
            
    updated_task = task_store.load_task(task_id)
    if not updated_task:
        raise HTTPException(status_code=500, detail="Task state could not be reloaded.")
        
    return {
        "success": True,
        "data": updated_task,
        "error": None
    }


@router.get("/{task_id}", response_model=dict)
async def get_task(task_id: str):
    """Fetches the state, plan, progress steps, and artifacts of a specific task."""
    task = task_store.load_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail=f"Task '{task_id}' not found")
    return {
        "success": True,
        "data": task,
        "error": None
    }


@router.get("", response_model=dict)
async def list_tasks():
    """Lists history of all multi-agent tasks, sorted newest first."""
    tasks = task_store.list_tasks()
    return {
        "success": True,
        "data": tasks,
        "error": None
    }


@router.put("/{task_id}/plan", response_model=dict)
async def update_plan(task_id: str, plan: ExecutionPlan):
    """Allows updating/modifying the step configurations prior to starting execution."""
    task = task_store.load_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail=f"Task '{task_id}' not found")
    if task.status not in ["pending_approval", "planning_failed"]:
        raise HTTPException(
            status_code=400,
            detail=f"Cannot update plan for task in status '{task.status}'. Plan is already finalized or running."
        )
        
    task.plan = plan
    task.status = "pending_approval"  # Reset status if it was planning_failed
    task.updated_at = datetime.now().isoformat()
    task_store.save_task(task)
    
    return {
        "success": True,
        "data": task,
        "error": None
    }


@router.post("/{task_id}/confirm", response_model=dict)
async def confirm_task(task_id: str, background_tasks: BackgroundTasks):
    """Approves the plan and starts sequential worker execution asynchronously."""
    task = task_store.load_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail=f"Task '{task_id}' not found")
    if task.status not in ["pending_approval", "failed", "cancelled"]:
        raise HTTPException(
            status_code=400,
            detail=f"Task is in '{task.status}', cannot transition to execution. Require 'pending_approval' or failed/cancelled state."
        )
        
    now_iso = datetime.now().isoformat()
    task.status = "executing"
    task.approved_at = now_iso
    task.updated_at = now_iso
    task.error = None
    
    # Initialize/Reset step results and plan step statuses
    for step in task.plan.steps:
        if step.step_id not in task.step_results:
            task.step_results[step.step_id] = StepResult(
                step_id=step.step_id,
                status="pending"
            )
        else:
            res = task.step_results[step.step_id]
            if res.status in ["failed", "skipped"]:
                res.status = "pending"
                res.error = None
                step.status = "pending"
                
    task_store.save_task(task)
    background_tasks.add_task(run_execution_graph, task_id)
    
    return {
        "success": True,
        "data": task,
        "error": None
    }


@router.post("/{task_id}/cancel", response_model=dict)
async def cancel_task(task_id: str):
    """Cancels a running execution, stopping at the next step boundary."""
    task = task_store.load_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail=f"Task '{task_id}' not found")
    if task.status != "executing":
        raise HTTPException(status_code=400, detail=f"Cannot cancel task in '{task.status}' state.")
        
    now_iso = datetime.now().isoformat()
    task.status = "cancelled"
    task.error = StepError(
        error_type="cancelled",
        message="Task execution was cancelled by the user.",
        details={}
    )
    task.completed_at = now_iso
    task.updated_at = now_iso
    
    # Set pending/running steps to cancelled/failed
    for step in task.plan.steps:
        if step.status in ["running", "pending"]:
            step.status = "cancelled"
        if step.step_id in task.step_results:
            res = task.step_results[step.step_id]
            if res.status in ["running", "pending"]:
                res.status = "failed"
                res.error = StepError(
                    error_type="cancelled",
                    message="Cancelled by user action.",
                    details={}
                )
                res.completed_at = now_iso
                
    task_store.save_task(task)
    
    return {
        "success": True,
        "data": task,
        "error": None
    }


@router.post("/{task_id}/steps/{step_id}/retry", response_model=dict)
async def retry_step(task_id: str, step_id: str, background_tasks: BackgroundTasks):
    """
    Performs downstream step invalidation, increments the step retry count,
    resets step and task statuses, and resumes execution in the background.
    """
    task = task_store.load_task(task_id)
    if not task:
        raise HTTPException(status_code=404, detail=f"Task '{task_id}' not found")
    if task.status not in ["completed", "failed", "cancelled", "executing"]:
        raise HTTPException(
            status_code=400,
            detail=f"Cannot retry step for task in '{task.status}' state."
        )
        
    # Check that step_id exists
    step_exists = any(step.step_id == step_id for step in task.plan.steps)
    if not step_exists:
        raise HTTPException(status_code=404, detail=f"Step '{step_id}' not found in execution plan.")
        
    # Apply invalidation
    invalidate_downstream_steps(task, step_id)
    
    # Clear top-level errors and final outcomes
    task.final_summary = None
    task.error = None
    task.status = "executing"
    task.updated_at = datetime.now().isoformat()
    
    task_store.save_task(task)
    background_tasks.add_task(run_execution_graph, task_id)
    
    return {
        "success": True,
        "data": task,
        "error": None
    }
